name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build -- --configuration production

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Save SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server using rsync
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" \
          dist/* \
          ${{ secrets.DO_USERNAME }}@${{ secrets.DO_HOST }}:${{ secrets.DO_DEPLOY_PATH }}

      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
            echo "Deploy realizado com sucesso!"
